import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from pyspark.sql.functions import col, create_map, lit, chain

# Logic generated by Amazon Q
# Prompt: "Generate PySpark logic to map ICD-10 Diabetes codes to RxHCC 2026 categories and flag mismatching NDCs."

def apply_rxhcc_mapping(df):
    """
    Applies 2026 RxHCC Mapping logic.
    Logic generated via Amazon Q natural language prompt.
    """
    
    # -------------------------------------------------------------------------
    # AMAZON Q GENERATED LOGIC START
    # -------------------------------------------------------------------------
    # Mapping Dictionary (Simulated 2026 Draft Model)
    # RxHCC30: Diabetes with Complications
    # RxHCC31: Diabetes without Complications
    # RxHCC29: Anti-Diabetic Drugs (Rx mapping, not Dx, but related)
    
    df_mapped = df.withColumn("RxHCC_2026", 
        when(col("diagnosis_code") == "E11.42", lit("RxHCC30")) # DM w/ Polyneuropathy
        .when(col("diagnosis_code") == "E11.69", lit("RxHCC30")) # DM w/ other complications
        .when(col("diagnosis_code") == "E11.9", lit("RxHCC31"))  # DM no complications
        .when(col("diagnosis_code") == "E11.A", lit("No_Risk_Score")) # Remission
        .otherwise(lit("Unmapped"))
    )
    
    # Cross-walk Logic: Verify diagnosis supports the drug claim (NDC)
    # Example: If on Insulin but code is E11.A (Remission), flag for review.
    # This is a 'Consistency Check' generated by Q.
    
    df_validated = df_mapped.withColumn("Data_Integrity_Flag",
        when((col("RxHCC_2026") == "No_Risk_Score") & (col("drug_class") == "Insulin"), "WARNING: Insulin prescribed for Pt in Remission")
        .when((col("diagnosis_code") == "E11.9") & (col("secondary_diagnosis") == "G62.9"), "SUGGESTION: Update to E11.42 for RxHCC30 capture")
        .otherwise("OK")
    )
    # -------------------------------------------------------------------------
    # AMAZON Q GENERATED LOGIC END
    # -------------------------------------------------------------------------
    
    return df_validated

def main():
    sc = SparkContext()
    glueContext = GlueContext(sc)
    spark = glueContext.spark_session
    job = Job(glueContext)
    
    # Load Data
    datasource0 = glueContext.create_dynamic_frame.from_catalog(database = "healthcare_db", table_name = "claims_raw")
    df = datasource0.toDF()
    
    # Apply Mapping
    df_transformed = apply_rxhcc_mapping(df)
    
    # Write back to S3
    df_transformed.write.parquet("s3://healthcare-analytics/rxhcc_mapped/2026/")
    
    job.commit()

if __name__ == "__main__":
    main()
